// Machine-readable error codes for client-side error handling
const ERROR_CODES = Object.freeze({
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',

  // User
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  USERNAME_COOLDOWN: 'USERNAME_COOLDOWN',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Contact / Relationships
  ALREADY_CONTACTS: 'ALREADY_CONTACTS',
  REQUEST_ALREADY_SENT: 'REQUEST_ALREADY_SENT',
  CONTACT_NOT_FOUND: 'CONTACT_NOT_FOUND',
  SELF_ACTION_NOT_ALLOWED: 'SELF_ACTION_NOT_ALLOWED',
  USER_BLOCKED: 'USER_BLOCKED',

  // Chat
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  NOT_CHAT_MEMBER: 'NOT_CHAT_MEMBER',
  SELF_CHAT_NOT_ALLOWED: 'SELF_CHAT_NOT_ALLOWED',

  // Message
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_NOT_OWNER: 'MESSAGE_NOT_OWNER',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_OTP: 'INVALID_OTP',
  OTP_EXPIRED: 'OTP_EXPIRED',

  // File
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',

  // General
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

module.exports = { ERROR_CODES };
